### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by BackSeat** [davep/textual-astview#10]
Just installed via pip and fired up `astare` and was presented with this:

```
$ astare app/musicmuster.py 
Traceback (most recent call last):
  File "/home/kae/.local/bin/astare", line 5, in <module>
    from textual_astview.app.astare import main
  File "/home/kae/.local/lib/python3.9/site-packages/textual_astview/__init__.py", line 16, in <module>
    from .widgets.node_info   import NodeInfo
  File "/home/kae/.local/lib/python3.9/site-packages/textual_astview/widgets/node_info.py", line 11, in <module>
    from .source_info import SourceInfo
  File "/home/kae/.local/lib/python3.9/site-packages/textual_astview/widgets/source_info.py", line 19, in <module>
    class SourceInfo( Vertical ):
  File "/home/kae/.local/lib/python3.9/site-packages/textual_astview/widgets/source_info.py", line 40, in SourceInfo
    def file_location_of( cls, node: ASTNode ) -> tuple[ int, int, int, int ] | None:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
```

**Comment by davep** [comment]
Hey Keith (there's a name I recognise from my previous employer ;-)). What version of Python are you attempting to run with? [3.9 or later](https://github.com/davep/textual-astview/blob/47408dff4900a452cff114eae914f753413944fc/setup.cfg#L39) is currently required (although that's currently just going off what `vermin` says -- I've no personally tested with 3.9 yet).

**Comment by BackSeat** [comment]
Hi Dave (I did wonder whether it was you when your name popped up on Mastodon!).

```
$ python --version
Python 3.9.2
```

**Comment by davep** [comment]
Cool, thanks. Testing with 3.9 here now it seems that some of the type hints really don't play well with that version (mainly I'm working on this with 3.11 at the moment). I'll dig around a bit and see if there's a not-too-painful way to keep 3.9 happy (and also run with 3.10 too to be sure).

**Comment by davep** [comment]
Tweaked some of the typing and in testing here it's all good on 3.9 as well now. Thanks again.
